apiVersion: v1
kind: Service
metadata:
  name: ai-minutes-frontend-lb
  labels:
    app: ai-minutes-frontend
spec:
  type: LoadBalancer
  selector:
    app: ai-minutes-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
